#!/usr/bin/env node

/**
 * app-ads.txt auto-updater
 * Fetches entries from ad networks and merges with constant entries.
 * Outputs a merged app-ads.txt to the project root.
 */

const https = require("https");
const fs = require("fs");
const path = require("path");

// ─────────────────────────────────────────────
// CONFIG — edit these with your real publisher IDs
// ─────────────────────────────────────────────

const CONSTANT_ENTRIES = {
  admob: [
    "google.com, pub-XXXXXXXXXXXXXXXX, DIRECT, f08c47fec0942fa0",
  ],
  facebook: [
    "facebook.com, XXXXXXXXXXXXXXXXXX, DIRECT",
  ],
};

const LIVE_NETWORKS = {
  unity: "https://ssp.unityads.unity3d.com/app-ads.txt",
  mintegral: "https://www.mintegral.com/app-ads.txt",
  applovin: "https://app-ads.txt.applovin.com/app-ads.txt",
  yandex: "https://yandex.com/legal/ads_sdk/app-ads.txt",
};

const OUTPUT_FILE = path.join(__dirname, "..", "app-ads.txt");

// ─────────────────────────────────────────────
// FETCH HELPER
// ─────────────────────────────────────────────

function fetchUrl(url) {
  return new Promise((resolve, reject) => {
    const req = https.get(url, { timeout: 15000 }, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        return fetchUrl(res.headers.location).then(resolve).catch(reject);
      }
      if (res.statusCode !== 200) {
        return reject(new Error(`HTTP ${res.statusCode} for ${url}`));
      }
      let data = "";
      res.on("data", (chunk) => (data += chunk));
      res.on("end", () => resolve(data));
    });
    req.on("timeout", () => { req.destroy(); reject(new Error(`Timeout: ${url}`)); });
    req.on("error", reject);
  });
}

function parseEntries(text) {
  return text
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith("#") && l.includes(","));
}

// ─────────────────────────────────────────────
// MAIN
// ─────────────────────────────────────────────

async function main() {
  const timestamp = new Date().toUTCString();
  const results = {};
  const errors = [];

  console.log("Fetching live networks...\n");

  await Promise.all(
    Object.entries(LIVE_NETWORKS).map(async ([name, url]) => {
      try {
        const text = await fetchUrl(url);
        const entries = parseEntries(text);
        results[name] = entries;
        console.log(`  ✓ ${name.padEnd(12)} ${entries.length} entries`);
      } catch (err) {
        errors.push({ name, err: err.message });
        results[name] = [];
        console.error(`  ✗ ${name.padEnd(12)} FAILED — ${err.message}`);
      }
    })
  );

  if (errors.length > 0) {
    console.warn(`\nWarning: ${errors.length} network(s) failed to fetch.`);
    console.warn("Their sections will be empty in the output.\n");
  }

  // Build the merged file
  const lines = [
    `# app-ads.txt`,
    `# Auto-generated by update-app-ads.js`,
    `# Last updated: ${timestamp}`,
    `#`,
    `# DO NOT EDIT MANUALLY — changes will be overwritten on next run.`,
    `# Edit scripts/update-app-ads.js to change constant entries.`,
    ``,
    `# ── AdMob (constant) ────────────────────────────────────────────`,
    ...CONSTANT_ENTRIES.admob,
    ``,
    `# ── Facebook (constant) ─────────────────────────────────────────`,
    ...CONSTANT_ENTRIES.facebook,
    ``,
    `# ── Unity (auto-fetched) ─────────────────────────────────────────`,
    ...results.unity,
    ``,
    `# ── Mintegral (auto-fetched) ─────────────────────────────────────`,
    ...results.mintegral,
    ``,
    `# ── AppLovin (auto-fetched) ──────────────────────────────────────`,
    ...results.applovin,
    ``,
    `# ── Yandex (auto-fetched) ────────────────────────────────────────`,
    ...results.yandex,
  ];

  const totalEntries = [
    ...CONSTANT_ENTRIES.admob,
    ...CONSTANT_ENTRIES.facebook,
    ...results.unity,
    ...results.mintegral,
    ...results.applovin,
    ...results.yandex,
  ].length;

  fs.writeFileSync(OUTPUT_FILE, lines.join("\n") + "\n", "utf8");

  console.log(`\nDone. ${totalEntries} total entries written to app-ads.txt`);

  // Exit with error code if all live networks failed (so CI can catch it)
  if (errors.length === Object.keys(LIVE_NETWORKS).length) {
    console.error("All live networks failed. Exiting with error.");
    process.exit(1);
  }
}

main().catch((err) => {
  console.error("Unexpected error:", err);
  process.exit(1);
});
